application: zyumaportfolio
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "4d 5h"

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: blog.application

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
